#!groovy

// Generated by IBM TransformationAdvisor
// Tue Jan 08 18:14:16 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '-X initialize process-resources verify'
    test='false'
}